name: Code Scanning
on:
  push:
    branches:
      - frontend
      - backend
      - master
jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/init@v1
        with: 
            languages: js, css, html